[package]
name = "vi-shaders"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib", "lib"]

[dependencies]
vi-common = { path = "../vi-common" }
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu", features = ["glam"] }